---
---



## About

The purpose of the Mathematical Sociology Section of the American Sociological Association (ASA) is to encourage, enhance and foster research, teaching and other professional activities in mathematical sociology, for the development of sociology and the benefit of society, through organized meetings, conferences, newsletters, publications, awards, and other means deemed appropriate by the Section Council. The Section seeks to promote communication, collaboration, and consultation among scholars in sociology in general, mathematical sociology, and allied scientific disciplines. 

# Section Council 

Chair: Lynn Smith-Lovin, Duke University<br>
Chair-Elect: Dawn T. Robinson, University of Georgia<br>
Past Chair: Guillermina Jasso, New York University<br>
Section Secretary/Treasurer: Pamela Emanuelson, North Dakota State University<br>
Weihua An, Emory University<br>
Matthew E. Brashears, University of South Carolina-Columbia<br>
Neha Gondal, Boston University<br>
Kevin Lewis, University of California-San Diego<br>
Victoria Money, University of South Carolina (Student Representative)<br>
Kimberly Brooke Rogers, Dartmouth College<br>
Emma Spiro, University of Washington<br>

# Mathematical Sociology Twitter

<a class="twitter-timeline" href="https://twitter.com/Math_Sociology?ref_src=twsrc%5Etfw">Tweets by Math_Sociology</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# Webpage Manager
[Zack W. Almquist](http://depts.washington.edu/), Assistant Professor of Sociology and Senior Data Science Fellow, eScience Institute & Core Training Director CSDE





